### ISSUE TITLE
fetch key not found: "MAILCHIMP_API_KEY"

### ISSUE THREAD

**Issue by kikocastro** [RailsApps/rails-stripe-checkout#3]
hi, just installed and selected none for the mail options and yet I get 

`rails s                                                                                               [5:14:02 PM]
=> Booting WEBrick
=> Rails 4.2.1 application starting in development on http://localhost:3000
=> Run`rails server -h`for more startup options
=> Ctrl-C to shutdown server
Exiting
(erb):18:in`fetch': key not found: "MAILCHIMP_API_KEY" (KeyError)
    from (erb):18:in `<main>'
`

**Comment by DanielKehoe** [comment]
Just change the _config/secrets.yml_ file. You need to set the MAILCHIMP_API_KEY value in either your Unix ENV variables or the _config/secrets.yml_ file.
