### ISSUE TITLE
Links in README lead to nonexistant app

### ISSUE THREAD

**Issue by ybur-yug** [RailsApps/rails-stripe-checkout#4]
Pretty self explanatory. Is there an official announcement on why? Just curious.

**Comment by kathyonu** [comment]
It would help greatly to be specific when pointing out one or more broken links.

**Comment by ybur-yug** [comment]
Sorry! I'm a loon and opened this on the wrong repository anyways :crying_cat_face: opening in the right spot and will document the specific lines w/links & closing
